include: package:lint/analysis_options.yaml

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
    yield_of_invalid_type: false
    avoid_classes_with_only_static_members: false
    constant_identifier_names: false
    argument_type_not_assignable: false
